### PR TITLE
Fixing python2 shutil import

### PR DESCRIPTION
**Pull request by hduarte**

### CODE REVIEW

**Comment by jtpereyda** [comment]
@hduarte If we're using a new package, it should go in `setup.py`. But, does `shutil_backports` even exist? I can't seem to install it with Pip:
```
> sudo -H python -m pip install --upgrade shutil_backports
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting shutil_backports
  ERROR: Could not find a version that satisfies the requirement shutil_backports (from versions: none)
ERROR: No matching distribution found for shutil_backports
```

**Comment by hduarte** [comment]
@jtpereyda the name of the package is correct, but the name of its usage is different hence the patch. Check the output bellow:

root@kali:~# pip2 install backports.shutil_get_terminal_size
Collecting backports.shutil_get_terminal_size
  Downloading https://files.pythonhosted.org/packages/7d/cd/1750d6c35fe86d35f8562091737907f234b78fdffab42b29c72b1dd861f4/backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Installing collected packages: backports.shutil-get-terminal-size
Successfully installed backports.shutil-get-terminal-size-1.0.0

root@kali:~# pip2 uninstall backports.shutil_get_terminal_size
Uninstalling backports.shutil-get-terminal-size-1.0.0:
  Would remove:
    /usr/local/lib/python2.7/dist-packages/backports.shutil_get_terminal_size-1.0.0.dist-info/*
    /usr/local/lib/python2.7/dist-packages/backports/*
    /usr/local/lib/python2.7/dist-packages/**shutil_backports**/*
Proceed (y/n)? ^COperation cancelled by user

root@kali:~# python
Python 2.7.16 (default, Apr  6 2019, 01:42:57) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> **from backports.shutil_get_terminal_size import get_terminal_size**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**ImportError: No module named shutil_get_terminal_size**
>>> **from shutil_backports import get_terminal_size**
>>> get_terminal_size()
terminal_size(columns=91, lines=24)
>>>

**Comment by jtpereyda** [comment]
@hduarte OK, it works when I pip install `backports.shutil_get_terminal_size`. Although after installing, I can use either of the import styles:
```
> python                                                                                        
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)                                               
[GCC 7.3.0] on linux2                                                                           
Type "help", "copyright", "credits" or "license" for more information.
>>> from backports.shutil_get_terminal_size import get_terminal_size
Traceback (most recent call last):                                                              
  File "<stdin>", line 1, in <module>
ImportError: No module named shutil_get_terminal_size
>>> quit()

> sudo -H python -m pip install backports
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. 
Collecting backports             
  ERROR: Could not find a version that satisfies the requirement backports (from versions: none)                                                                                                

ERROR: No matching distribution found for backports       

> sudo -H python -m pip install backports.shutil_get_terminal_size                              
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.                                                                            
Collecting backports.shutil_get_terminal_size                                                     
  Downloading https://files.pythonhosted.org/packages/7d/cd/1750d6c35fe86d35f8562091737907f234b78fdffab42b29c72b1dd861f4/backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl 
ERROR: boofuzz 0.1.5 has requirement Flask~=1.0, but you'll have flask 0.10.1 which is incompatible. 
Installing collected packages: backports.shutil-get-terminal-size                               
Successfully installed backports.shutil-get-terminal-size-1.0.0  

> python                                                                                        
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)                                               
[GCC 7.3.0] on linux2                                                                           
Type "help", "copyright", "credits" or "license" for more information.                          
>>> from backports.shutil_get_terminal_size import get_terminal_size as t                       
>>> from shutil_backports import get_terminal_size as t2                                        
>>> t()                                                                                         terminal_size(columns=237, lines=63)
>>> t2()                                                                                        terminal_size(columns=237, lines=63)
```

It's a bit curious, though I suppose it shouldn't hurt to change to the approach you have here in this PR.

**Comment by hduarte** [comment]
That's strange, I have tested in a CentOS and Kali linux, with different python2 versions, and always got the same behaviour.

**Comment by jtpereyda** [comment]
FWIW, my attempt above as on Ubuntu WSL, 64 bit.

I'll leave this open for a bit in case anyone else has further insight, but I'm OK with merging.

**Comment by hduarte** [comment]
Agreed. Thanks for the help in checking this ;)

**Pull request merged**
