### PR TITLE
Split boofuzz/sessions.py

### PR DESCRIPTION
**Pull request by hackathi**
For the plan behind this madness, see #637.

Tox says everything is fine with splitting this module into a subpackage. I'll mark this PR as WIP and add to it as I get stuff done.

### CODE REVIEW

**Comment by mistressofjellyfish** [comment]
On second thought, I think it'd be better to merge these independently as I don't have a timeline on when I have more code to share.

**Review by SR4ven — CHANGES_REQUESTED** [review]
LGTM, thanks @mistressofjellyfish!

Once those line length errors are fixed we're good to go from my side.

**Comment by jtpereyda** [comment]
@mistressofjellyfish This is just splitting into several files? LGTM. Agree on merging and making other changes separately. Let's fix the Stickler issues like @SR4ven mentioned and get it merged. Cheers!

**Review by SR4ven — APPROVED** [review]

**Comment by SR4ven** [comment]
Thanks again @hackathi! Merging now.

**Pull request merged**
