### PR TITLE
Fixed s_random value type

### PR DESCRIPTION
**Pull request by SR4ven**
Possibly a fix for #290 
@kleest @cq674350529 please test and verify.

### CODE REVIEW

**Comment by cq674350529** [comment]
@SR4ven It seems to work. Thanks.

PS: First I wonder why it works because the type of `self._original_value` differs from that of `self._value`.  
In my view, I would like to change `self._value = self._original_value = str(value)` to `self._value = self._original_value = helpers.str_to_bytes(value)`. Actually, it's already done in the `BasePrimitive`.

https://github.com/jtpereyda/boofuzz/blob/0e48caa4e022e6e35908a19bdb988fec31b98e64/boofuzz/primitives/base_primitive.py#L62-L86

**In addition, there are many cases like this in other places.**

https://github.com/jtpereyda/boofuzz/blob/0e48caa4e022e6e35908a19bdb988fec31b98e64/boofuzz/utils/scada.py#L19-L20

**Comment by cq674350529** [comment]
Forgot to say, `six.binary_type(b"")` is used in other places, as well as `b""`.  I'm not familiar with the py2 and py3 compatibility.

**Comment by SR4ven** [comment]
We could use `self._value = self._original_value = helpers.str_to_bytes(value)` and `six.binary_type(b"")` but it appears to make no difference. For type consistency reasons, we should probably do this.
@jtpereyda what do you think?

**Comment by jtpereyda** [comment]
`self._value = self._original_value = helpers.str_to_bytes(value)` seems reasonable enough. One of the effects of using `str(value)` is that it would normalize some types to `str`, but I don't know that that's particularly important or relevant. By using `helpers.str_to_bytes(value)`, the type will accept either `bytes` or `str` which seems good enough to me.

From the [six docs](https://buildmedia.readthedocs.org/media/pdf/six/latest/six.pdf): 

> six.binary_type
> Type for representing binary data. This is str in Python 2 and bytes in Python 3. Python 2.6 and 2.7 include
> bytes as a builtin alias of str, so six’s version is only necessary for Python 2.5 compatibility

So `b""` should get us enough compatibility -- v2.5 isn't a compatibility target.

**Comment by jtpereyda** [comment]
Thank you @SR4ven and @cq674350529 ! Once discussed changes are implemented, we could merge. Has anyone tested the use case from the original issue?

**Comment by SR4ven** [comment]
I have to correct myself, `self._value = self._original_value = helpers.str_to_bytes(value)` works when running a fuzz session, but fails the unit tests.
```python
_____________________________ ERROR collecting unit_test.py ______________________________
unit_test.py:5: in <module>
    unit_tests.test_blocks.run()
unit_tests/test_blocks.py:11: in run
    repeaters()
unit_tests/test_blocks.py:121: in repeaters
    data = s_render()
boofuzz/__init__.py:113: in s_render
    return blocks.CURRENT.render()
boofuzz/blocks/request.py:155: in render
    self._rendered += item.render()
boofuzz/blocks/block.py:232: in render
    self._rendered += item.render()
E   TypeError: cannot concatenate 'str' and 'int' objects
------------------------------------ Captured stdout -------------------------------------
PRIMITIVE MUTATION COUNTS (SIZES):
	delim:  44	(3979)
	string: 1441	(65927421)
	byte:   112
	word:   140
	dword:  140
	qword:  140
	sizer:  140
```

Running the fuzz session provided in the issue works with both approaches.

**Comment by jtpereyda** [comment]
See line 121 in test_blocks.py
```
        s_random(0, 5, 10, 100, name="random", fuzzable=False)
```
With the new change, the first argument would need to be `"0"` instead of `0`.

**Comment by SR4ven** [comment]
@jtpereyda thanks for the hint! Now it works.

**Comment by kleest** [comment]
With the latest changes, both the tests and my use case work fine. Thanks!

**Comment by jtpereyda** [comment]
Thanks all for the PR and fix!

**Pull request merged**
