### PR TITLE
Add with statement support to blocks

### PR DESCRIPTION
**Pull request by cbisnett**
Added support for automatically scoping blocks using Python's `with` statement. For example what used to be written like this:
```
if s_block_start("myblock"):
    s_string("foobar")
    ...
s_block_end()
```
Can now be simplified to this:
```
with s_block("myblock"):
    s_string("foobar")
    ...
```

---
This change is [Reviewable](https://reviewable.io/reviews/jtpereyda/boofuzz/121)

### CODE REVIEW

**Comment by cbisnett** [comment]
Actually now that I think about it, the default argument values aren't being passed when calling through `s_block_start()`. I'll update the branch.

**Comment by jtpereyda** [comment]
Very cool! Did you do a manual run of unit_test/blocks.py? I don't think it is included in the automatically run tests; IIRC some of them weren't passing, but if the new test you wrote is passing, that's probably fine.

**Comment by jtpereyda** [comment]
I would try now but I'm having issues on my current system.

**Comment by jtpereyda** [comment]
I got my system up and tested it. Good to go. Thank you for the contributions! Feel free to add yourself to the CONTRIBUTORS.txt file.

**Pull request merged**
