### PR TITLE
Documentation improve

### PR DESCRIPTION
**Pull request by MetinSAYGIN**
For ticket #521

Here is a small example, i don't know if i have to go deeper on it because it's for quickstart section.
Should be worth to pull it for beginners.

Metin

### CODE REVIEW

**Review by jtpereyda — CHANGES_REQUESTED** [review]
@MetinSAYGIN Thanks for the PR! This is a simple and helpful improvement. I think there will be some editorial changes, but for starters, have you rendered the docs to check the format? See `tox.ini` which has the sphinx build commands. You can build locally and check out the rendered HTML.

Edit: For example, I think this bit will look funny once built:
```
To perform this test, you will need an HTTP server, you can use python for that.
python3 -m http.server
Then run the http_simple.py script on the ip/port that the server use.
```

**Comment by MetinSAYGIN** [comment]
Hi @jtpereyda, it should be better now :)
Metin

**Comment by jtpereyda** [comment]
Thank you for the docs contribution @MetinSAYGIN !

**Review by jtpereyda — APPROVED** [review]

**Comment by SR4ven** [comment]
No one approved the test runs on this PR and now the docs fail to build:
https://github.com/jtpereyda/boofuzz/actions/runs/4515478396/jobs/7952811037

**Comment by jtpereyda** [comment]
@SR4ven Oh, hmm, that's my bad isn't it? I saw all green checkmarks and just hit merge 😬

**Comment by SR4ven** [comment]
No worries @jtpereyda, I'll fix it later.
The reason for this is that first time PR submitters have to get GitHub Actions approved manually.
SticklerCI apparently doesn't have this requirement so that's why u saw the green checkmark.

Also remember to squash and merge for clean history :D If I remember correctly, you can even set that as the default in the project settings.

**Comment by jtpereyda** [comment]
@SR4ven they have to approve Actions in their own settings?

[From what I could find](https://stackoverflow.com/a/49416216/461834):

> The GitHub user interface will default the option to the last option selected by the user for the current project.

So I'll just have to be more careful next time.

**Comment by SR4ven** [comment]
@jtpereyda no we have to approve test runs on PRs from users that haven't contributed to the project yet.

Yeah right, that's how the default option works.
I confused this with a general project setting in the Pull Request section. There you can disallow certain merge strategies.

**Pull request merged**
