### PR TITLE
Removed misleading information

### PR DESCRIPTION
**Pull request by ptdropper**
Removed misleading information, Clarified intent.

### CODE REVIEW

**Comment by ptdropper** [comment]
I do not know what the issue is that caused "Test / Python 3.9 on windows-latest (pull_request) Cancelled after 15m" 
Any suggestions are welcome.

**Comment by jtpereyda** [comment]
Looks like the test fixed with a re-run. Thanks for the PR @ptdropper !

**Comment by jtpereyda** [comment]
@SR4ven is this one good to merge?

**Comment by ptdropper** [comment]
Hi,

 I'm open to suggestions on what would be the next priority item to work in
the boofuzz project.

Robert Smigielski ***@***.***

**Comment by jtpereyda** [comment]
@ptdropper I think there's a general need for documentation and examples. On the coding side, https://github.com/jtpereyda/boofuzz/issues/88 is one mildly complex and frequently requested feature.

**Comment by SR4ven** [comment]
@jtpereyda yup, good to go.

**Pull request merged**
