### PR TITLE
Fix max_size of string primitive

### LINKED ISSUE #487: max_len invalid in s_string() ？
Test script:
```py
from boofuzz import *

def main():
    session = Session(
        target=Target(
            connection=SocketConnection("127.0.0.1", 1234, proto='tcp')
        ),
    )

    s_initialize(name="test")

    s_string("abcd", max_len=100)
    session.connect(s_get("test"))

    session.fuzz()


if __name__ == "__main__":
    main()
```

length of generated data should within 100, but i got 500000:
```
[2021-01-31 20:41:56,971] Test Case: 1292: test:test.String1:1292
[2021-01-31 20:41:56,971]     Info: Type: String. Default value: b''. Case 1292 of 1482 overall.
[2021-01-31 20:41:56,971]     Info: Opening target connection (192.168.1.5:1234)...
[2021-01-31 20:41:56,971]     Info: Connection opened.
[2021-01-31 20:41:56,971]   Test Step: Monitor CallbackMonitor#139659426646224[pre=[],post=[],restart=[],post_start_target=[]].pre_send()
[2021-01-31 20:41:56,971]   Test Step: Fuzzing Node 'test'
[2021-01-31 20:41:57,064]     Info: Sending 500000 bytes...
```

pkts in wireshark:
截屏2021-01-31 下午8 49 03

Is this a bug?

### PR DESCRIPTION
**Pull request by SR4ven**
@kuraraneko can you verify that this fixes #487?

### CODE REVIEW

**Comment by SR4ven** [comment]
Currently we only yield strings which are within the defined max_len.
In the bytes primitive we yield all values and truncate them to the max_len.

Should we unify this behaviour @jtpereyda?

**Comment by kuraraneko** [comment]
The generated data of s_string() seem to be normal, I think the bug has been fixed.

**Comment by jtpereyda** [comment]
@SR4ven Truncate would be nice. If it's too tricky though we can fall back on skipping long strings. Naive truncation would result in some duplicates, so that's at least one tricky detail.

**Comment by jtpereyda** [comment]
Code looks good to merge for now. Feel free to implement truncation now/later/never at your preference. :)

Thanks @kuraraneko for the report and @SR4ven for the fix!

**Comment by SR4ven** [comment]
Sounds good, I'll merge now and implement the truncation later.
Still need to figure out a way to prevent duplicates

**Pull request merged**
