### PR TITLE
Fuzzer example for "vulnserver"

### PR DESCRIPTION
**Pull request by pedroflor**
Functional example of fuzzing "vulnserver.exe".
The latest version of boofuzz was used.

### CODE REVIEW

**Comment by jtpereyda** [comment]
@pedroflor Very cool! One request:
1. Would you mind adding a line to CHANGELOG.rst to the effect of `- Added fuzzer for vulnserver`?

**Comment by SR4ven** [comment]
@pedroflor you seem to have "allow edits from maintainers" disabled, and Stickler-CI can't push black style fixes to your branch.
I don't think it's anything major, but please make sure that you meet the style guide.
The easiest way would be to enable said option and push a commit.

**Comment by pedroflor** [comment]
Enabled "Allow edits from maintainers."

**Comment by pedroflor** [comment]
I'm so sorry... I don't know how to do that... I'm googling...

**Comment by pedroflor** [comment]
> I'm so sorry... I don't know how to do that... I'm googling...

Shame on me... Could you help me please fixing that problem?

**Comment by SR4ven** [comment]
@pedroflor there should be a tick box on the right side of this page.
https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork
After that, the check has to be triggered again, either manually by @jtpereyda or by pushing a commit to this branch on your fork, just as you did before. e.g. update the changelog.

You could always run the style check locally with [black](https://github.com/psf/black) just install it with `pip install black` and then run `black .` in the boofuzz directory.

**Pull request closed without merging**
